<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/connection.php';
require_alumni();

$pageTitle = 'Dashboard';
$userName = current_user_name();
$userEmail = $_SESSION['user_email'] ?? '';
$events = [];
$stmt = mysqli_prepare($connection, "SELECT title,event_date,event_time,location FROM events_announcements WHERE active=1 AND (event_date>=CURDATE() OR end_date>=CURDATE()) ORDER BY event_date ASC LIMIT 5");
if ($stmt) { mysqli_stmt_execute($stmt); $result=mysqli_stmt_get_result($stmt); while($row=mysqli_fetch_assoc($result)) $events[]=$row; mysqli_stmt_close($stmt); }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard | AlumTrace</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/css/alumtrace.css"></head><body><a class="skip-link" href="#main">Skip to content</a><?php require __DIR__.'/includes/sidebar.php'; ?><div class="main-wrapper"><?php require __DIR__.'/includes/topbar.php'; ?><main class="content" id="main"><section class="welcome-banner"><h2>Welcome back, <?= htmlspecialchars($userName) ?>!</h2><p>Keep your alumni profile, career records, education, and community connections up to date.</p></section><div class="dashboard-grid"><section><div class="section-header"><h2>AlumTrace features</h2></div><div class="features-grid"><a class="feature-card featured" href="Profile.php"><i class="fa-solid fa-id-card card-icon"></i><h3>My Profile</h3><p>Update your personal and academic information.</p></a><a class="feature-card" href="Employment.php"><i class="fa-solid fa-briefcase card-icon"></i><h3>Employment</h3><p>Manage your work history and career milestones.</p></a><a class="feature-card" href="Education.php"><i class="fa-solid fa-certificate card-icon"></i><h3>Education</h3><p>Maintain credentials and certifications.</p></a><a class="feature-card" href="Directory.php"><i class="fa-solid fa-address-book card-icon"></i><h3>Directory</h3><p>Discover alumni and professional connections.</p></a><a class="feature-card" href="Survey.php"><i class="fa-solid fa-square-poll-horizontal card-icon"></i><h3>Surveys</h3><p>Share feedback with the institution.</p></a><a class="feature-card" href="Events.php"><i class="fa-solid fa-bullhorn card-icon"></i><h3>Events</h3><p>Stay informed about announcements.</p></a></div></section><aside class="right-sidebar"><div class="widget-card"><h3><i class="fa-solid fa-calendar-days"></i> Upcoming events</h3><?php if(!$events): ?><p class="muted">No upcoming events yet.</p><?php else: foreach($events as $event): ?><div class="event-item"><strong><?= htmlspecialchars($event['title']) ?></strong><small><?= htmlspecialchars(date('M j, Y',strtotime($event['event_date']))) ?><?= $event['location']?' · '.htmlspecialchars($event['location']):'' ?></small></div><?php endforeach; endif; ?><a class="view-all-events" href="Events.php">View all events</a></div></aside></div></main><?php require __DIR__.'/includes/dashboard-footer.php'; ?></div><script src="assets/js/alumtrace.js"></script></body></html>
